# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vesr}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Roman Simecek}]
  s.date = %q{2011-10-10}
  s.description = %q{VESR}
  s.email = %q{roman.simecek@cyt.ch}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/esr_bookings_controller.rb",
    "app/models/esr_file.rb",
    "app/models/esr_record.rb",
    "app/views/esr_bookings/_form.html.erb",
    "app/views/esr_bookings/_item.html.erb",
    "app/views/esr_bookings/_list_footer.html.erb",
    "app/views/esr_bookings/_list_header.html.erb",
    "app/views/esr_bookings/_list_records.html.erb",
    "app/views/esr_bookings/_navigation_section.html.erb",
    "app/views/esr_bookings/_sidebar.html.erb",
    "app/views/esr_bookings/list.html.erb",
    "app/views/esr_bookings/show.html.erb",
    "lib/vesr.rb",
    "lib/vesr/prawn.rb",
    "lib/vesr/prawn/esr_recipe.rb",
    "test/helper.rb",
    "test/test_vesr.rb",
    "vesr.gemspec"
  ]
  s.homepage = %q{http://github.com/raskhadafi/vesr}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.8}
  s.summary = %q{VESR}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<prawn>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<prawn>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<prawn>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

